### ISSUE TITLE
DevOps task error - not working in yaml build pipelines (only classic release)

### ISSUE THREAD

**Issue by tnsholding** [danielsollondon/azvmimagebuilder#67]
Trying to use the DevOps task in a yaml pipeline. But getting this error:

`##[error]TypeError: Cannot read property 'split' of null`

Seems some input is null - any idea what I could be missing?

This is my yaml for the task:

```
- task: AzureImageBuilderTask@1
  inputs:
    managedIdentity: '/subscriptions/<subid>/resourcegroups/<rg>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<uami-name>'
    imageSource: marketplace
    baseImagePubOfferSku: 'MicrosoftWindowsDesktop:office-365:20h1-evd-o365pp'
    provisioner: powershell
    packagePath: '$(Build.SourcesDirectory)/WVD'
    inlineScript: '& ''c:\buildArtifacts\WVD\Win10ms.ps1'''
    storageAccountName: <name of my storage account>
    distributeType: sig
    galleryImageId: '/subscriptions/<subid>/resourceGroups/<rg>/providers/Microsoft.Compute/galleries/<gallery name>/images/<image def name>'
    ibSubscription: '<service connection name>'
    ibAzureResourceGroup: '<rg name>'
    ibLocation: westeurope
```

**Comment by tnsholding** [comment]
Managed to get past the above error. Not sure exactly what setting was missing, but this is the updated yaml:

```
- task: AzureImageBuilder.devOps-task-for-azure-image-builder.custom-build-release-task.AzureImageBuilderTask@1
  displayName: 'Azure VM Image Builder Task'
  inputs:
    managedIdentity: '/subscriptions/<subid>/resourcegroups/<rg>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<uami-name>'
    imageSource: marketplace
    baseImage: 'MicrosoftWindowsDesktop:Windows-10:rs5-evd'
    baseImagePubOfferSku: 'MicrosoftWindowsDesktop:office-365:20h1-evd-o365pp'
    provisioner: powershell
    packagePath: WVD
    inlineScript: |
      & 'c:\buildArtifacts\Win10ms.ps1'
    storageAccountName: <name of my storage account>
    imageIdForDistribute: '/subscriptions/<subid>/resourceGroups/<rg>/providers/Microsoft.Compute/galleries/<gallery-name>/images/<image def name>'
    galleryImageId: '/subscriptions/<subid>/resourceGroups/<rg>/providers/Microsoft.Compute/galleries/<gallery-name>/images/<image def name>'
    managedImageLocation: westeurope
    ibSubscription: '<service connection name>'
    ibAzureResourceGroup: '<rg name>'
    ibLocation: westeurope
```

However I now face a different error:
`##[error]Error: post template call failed for template t_undefinedundefined_1597736470126 with error: Failed in distributing 1 images out of total 1: Some error happened, please check the error details. (CODE: 200)`

It seems to be caused by the task internally having a dependency on running as a release and not a build pipeline? 
If I look at the pipeline debug output, I see these lines:
```
Source for image:  { type: 'PlatformImage',
  publisher: 'MicrosoftWindowsDesktop',
  offer: 'office-365',
  sku: '20h1-evd-o365pp',
  version: '19041.450.2008080726' }
##[debug]release.releaseid=undefined
##[debug]release.attemptnumber=undefined
template name:  t_undefinedundefined_1597737329939
starting put template...
```

So it seems that the code internally uses release.releaseid and release.attemptnumber to create a unique template name. This does not work in a yaml build pipeline. 
Any plans to make the task work in both build and release pipelines?
